### PR TITLE
lib: make bpf.h local

### PR DESCRIPTION
**Pull request by williamtu**
Instead of using system's bpf.h (/usr/include/linux/bpf.h),
copy the latest bpf.h under lib/

### CODE REVIEW

**Comment by williamtu** [comment]
I will merge this, the error is due to:
```
[91m/usr/local/share/p4c/p4include/ebpf_model.p4(26): error: CounterArray shadows CounterArray
    CounterArray(bit<32> max_index, bool sparse);
    ^^^^^^^^^^^^
/usr/local/share/p4c/p4include/ebpf_model.p4(22)
extern CounterArray {
```
not this change

**Comment by mbudiu-vmw** [comment]
The haven't merged my PR fixing this issue into p4c.
I will prepare the master branch of p4c-clone, and let you know.

**Comment by williamtu** [comment]
it's ok, we can wait for the p4c. You are right, using local bpf.h will cause more problem later on. Let me revert it.

**Comment by mbudiu-vmw** [comment]
p4c-clone master should have removed the spurious warning.
But I don't know if you want travis to depend on p4c-clone.

**Comment by williamtu** [comment]
I want travis to build on p4c, if eventually we want to merge to p4c. What
do you think?

**Comment by mbudiu-vmw** [comment]
Yes, that sounds like a good approach. I don't know why they are taking so long to merge that PR.

**Comment by mbudiu-vmw** [comment]
The PR has been merged.

**Pull request merged**
